In [1]:
path=r'D:\firefox\wine.txt'
with open(path,'r') as f:
    content=f.readlines()
    print(content)


['1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065\n', '1,13.2,1.78,2.14,11.2,100,2.65,2.76,.26,1.28,4.38,1.05,3.4,1050\n', '1,13.16,2.36,2.67,18.6,101,2.8,3.24,.3,2.81,5.68,1.03,3.17,1185\n', '1,14.37,1.95,2.5,16.8,113,3.85,3.49,.24,2.18,7.8,.86,3.45,1480\n', '1,13.24,2.59,2.87,21,118,2.8,2.69,.39,1.82,4.32,1.04,2.93,735\n', '1,14.2,1.76,2.45,15.2,112,3.27,3.39,.34,1.97,6.75,1.05,2.85,1450\n', '1,14.39,1.87,2.45,14.6,96,2.5,2.52,.3,1.98,5.25,1.02,3.58,1290\n', '1,14.06,2.15,2.61,17.6,121,2.6,2.51,.31,1.25,5.05,1.06,3.58,1295\n', '1,14.83,1.64,2.17,14,97,2.8,2.98,.29,1.98,5.2,1.08,2.85,1045\n', '1,13.86,1.35,2.27,16,98,2.98,3.15,.22,1.85,7.22,1.01,3.55,1045\n', '1,14.1,2.16,2.3,18,105,2.95,3.32,.22,2.38,5.75,1.25,3.17,1510\n', '1,14.12,1.48,2.32,16.8,95,2.2,2.43,.26,1.57,5,1.17,2.82,1280\n', '1,13.75,1.73,2.41,16,89,2.6,2.76,.29,1.81,5.6,1.15,2.9,1320\n', '1,14.75,1.73,2.39,11.4,91,3.1,3.69,.43,2.81,5.4,1.25,2.73,1150\n', '1,14.38,1.87,2.38,12,102,3.3,3.64,.29,2.96,7.5,

In [2]:
import numpy as np

In [3]:
l1=[]
for i in range(len(content)):
   l1.append((np.array(content[i].rstrip('\n').split(',')).astype(float)))

In [4]:
l1=np.array(l1)

In [13]:
l1=l1[l1[:,0]!=3]

In [14]:
print(l1.shape)

(130, 14)


In [34]:
#python实现PCA
def pca(x,k):#k is the components you want
    # #mean of each feature
    n_samples, n_features = x.shape
    mean=np.array([np.mean(x[:,i]) for i in range(n_features)])
    #normalization
    norm_X=x-mean
    #scatter matrix
    scatter_matrix=np.dot(np.transpose(norm_X),norm_X)
    #calculate the eigenvectors and eigenvalues
    eig_val,eig_vec=np.linalg.eig(scatter_matrix)
    # print("各特征所占方差比例\n",eig_val/np.sum(eig_val))
    eig_pairs=[(np.abs(eig_val[i]),eig_vec[:,i]) for i in range(n_features)]
    # print("特征值及其特征向量\n",eig_pairs)
    #sort eig_vec based on the eig_val from high to lowest
    eig_pairs.sort(reverse=True)
    #select the top k eig_vec
    feature=np.array([ele[1] for ele in eig_pairs[:k]])
    # print(feature)
    #get new data
    data=np.dot(norm_X,np.transpose(feature))
    return data

In [42]:
print(pca(l1,3))

[[ 2.75383200e+02  2.19335652e+01 -2.46837775e+00]
 [ 2.59892890e+02 -4.86396814e+00 -6.35226053e+00]
 [ 3.94860853e+02 -6.23392937e+00  1.59123671e+00]
 [ 6.90046194e+02  2.47461123e-01  7.77978671e-01]
 [-5.47510462e+01  1.91614968e+01  1.65143704e+00]
 [ 6.60035024e+02 -2.28140776e-01 -8.74785801e-01]
 [ 4.99763422e+02 -1.32617894e+01 -1.86024993e+00]
 [ 5.05214889e+02  1.16826800e+01  7.71301698e-01]
 [ 2.54832930e+02 -7.71581817e+00 -3.68377902e+00]
 [ 2.54849326e+02 -6.67874839e+00 -1.79698554e+00]
 [ 7.19877396e+02 -8.29417174e+00  2.39471177e+00]
 [ 4.89735562e+02 -1.40453996e+01  2.93585038e-01]
 [ 5.29621423e+02 -2.07952083e+01 -2.18191572e-01]
 [ 3.59713424e+02 -1.57013199e+01 -5.65740873e+00]
 [ 7.56846720e+02 -1.20736362e+01 -3.48085213e+00]
 [ 5.20053619e+02  2.40574972e+00  4.48581655e-01]
 [ 4.90194788e+02  1.10098545e+01  3.00367963e+00]
 [ 3.40131283e+02  8.80010437e+00  2.35503771e+00]
 [ 8.89918346e+02 -8.47965843e+00  1.44513166e+00]
 [ 5.52180675e+01  1.50197207e+

In [43]:
print(pca(l1,3).shape)

(130, 3)


In [15]:
a=np.array([[-1,-1],[-2,-1],[-3,-2],[1,1],[2,1],[3,2]])
matrix=np.dot(np.transpose(a),a)
val,vec=np.linalg.eig(matrix)
pairs=[(np.abs(val[i]),vec[:,i]) for i in range(2)]
pairs.sort(reverse=True)
f=np.array([ele[1] for ele in pairs[:2]])
# np.dot(a,np.transpose(f))


In [17]:
pairs

[(39.69771560359221, array([0.83849224, 0.54491354])),
 (0.30228439640779037, array([-0.54491354,  0.83849224]))]

In [39]:
(val/np.sum(val))

array([0.99244289, 0.00755711])